### ISSUE TITLE
It doesn't make sense to show only one string, right

### ISSUE THREAD

**Issue by manondidi** [marcelgarus/marquee#10]
The vertical marquee displays multiple sets of text,
For example, regularly updated headlines,
What's the point of having only one line of text constantly scrolling, especially vertical

**Comment by marcelgarus** [comment]
Alright, I'll consider supporting multiple texts

**Comment by marcelgarus** [comment]
The marquee now has a `text` parameter that can be set alternatively to `text` and multiple texts will be displayed.

**Comment by francochau** [comment]
> The marquee now has a `texts` parameter that accepts a list of Strings and can be set alternatively to `text`, causing multiple texts to be displayed.

Is the texts prop still available to use?

**Comment by marcelgarus** [comment]
Sorry, doesn't look like it 👀
I may have been wrong in the comment above, but seems strange 🤔

**Comment by faisalmushtaq007** [comment]
@MarcelGarus  but it will be a great update if you implement list of strings. Much needed update!
