### ISSUE TITLE
I getting error on using marquee 

### ISSUE THREAD

**Issue by Milan-Verselix** [MarcelGarus/marquee#102]
../../../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:31: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't.
 - 'PageController' is from 'package:flutter/src/widgets/page_view.dart' ('../../../Library/Developer/flutter/packages/flutter/lib/src/widgets/page_view.dart').
 - 'ScrollController' is from 'package:flutter/src/widgets/scroll_controller.dart' ('../../../Library/Developer/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart').
      scrollController: child.controller,
      
      How to solve it ?

**Comment by GoranSustekJr** [comment]
Getting same issue here

**Comment by GoranSustekJr** [comment]
Have been searching around and in the following issue [https://github.com/MarcelGarus/marquee/issues/98](url) is the anwser.

**Comment by henriquemello** [comment]
https://github.com/MarcelGarus/marquee/issues/98 the anwser is here

**Comment by realitymolder** [comment]
Please update to 2.3
