### ISSUE TITLE
Update fading_edge_scrollview to 4.1.1

### ISSUE THREAD

**Issue by danielalanisgux** [MarcelGarus/marquee#103]
Hello bro, you need to upgrade fading_edge_scrollview to version 4.1.1 because the version 3.0.0 has an issue with PageController and ScrollController. Upgrading to 4.1.1 solve this

**Comment by BigYajuu** [comment]
This is truly disastrous, as the package does not work AT ALL now.

**Comment by danielalanisgux** [comment]
> This is truly disastrous, as the package does not work AT ALL now.

@BigYajuu I agree, as a temporal fix you can copy all the [marquee code](https://github.com/MarcelGarus/marquee/blob/master/lib/marquee.dart) to a local widget and delete marquee lib from pubspec, then install the fading_edge_scrollview 4.1.1 and the problem will be solved.

**Comment by Frogperson** [comment]
> > This is truly disastrous, as the package does not work AT ALL now.
> 
> @BigYajuu I agree, as a temporal fix you can copy all the [marquee code](https://github.com/MarcelGarus/marquee/blob/master/lib/marquee.dart) to a local widget and delete marquee lib from pubspec, then install the fading_edge_scrollview 4.1.1 and the problem will be solved.

An even easier solution is to simply add this to your `pubspec.yaml`
```yml
dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  ```

**Comment by danielalanisgux** [comment]
> > > This is truly disastrous, as the package does not work AT ALL now.
> > 
> > 
> > @BigYajuu I agree, as a temporal fix you can copy all the [marquee code](https://github.com/MarcelGarus/marquee/blob/master/lib/marquee.dart) to a local widget and delete marquee lib from pubspec, then install the fading_edge_scrollview 4.1.1 and the problem will be solved.
> 
> An even easier solution is to simply add this to your `pubspec.yaml`
> 
> ```yaml
> dependency_overrides:
>   fading_edge_scrollview: ^4.1.1
> ```

In my particular case, doing that cause a conflict beteween marquee lib pubsec and my project's one, so i didn't have another option, if that works for you great job!!

Cheers mate!

**Comment by realitymolder** [comment]
In the upcoming two days you will get an update to 2.3. 😎  be prepared.
