### ISSUE TITLE
Jerk while playing the example

### ISSUE THREAD

**Issue by rohitranjan1991** [marcelgarus/marquee#16]
First of all, thanks for this widget.

While using the marquee widget, the text jerks after every x seconds.
Phone: Samsung s9+
Orientation: Landscape

My Code is : 

 child: Marquee(
                          velocity: double.parse(_currentBanner.duration) / 100,
                          texts: [ 'Some sample text.', 'Some other text.' ],
                          blankSpace: 20.0,
                          pauseAfterRound: Duration(seconds: 0),
                          startPadding: 10.0,
                          style: TextStyle(fontSize: double.parse(_currentBanner.font_size), color: Utils.hexToColor(_currentBanner.font_color)),
                          scrollAxis: Axis.horizontal),
                    )

Can you please look into it.

**Comment by marcelgarus** [comment]
First of all, you're welcome. 😄

I'm sorry to hear about the performance problems.
Sadly, I don't have much spare time these days and I'm not actively using this widget in the app I'm currently working on, so it's not a priority for my right now.
That being said, you're very welcome to dig into the issue and contribute to this repo - I'm happy to accept pull requests.

A good first step would be to run your app in profiling mode (`flutter run --profile`).
That should give you an idea about where the performance bottleneck is.
If you found out which part of the code is causing the performance issues, I welcome you to post them here for future reference.

**Comment by danieldai** [comment]
In every round, it will jump to `_startPosition` which is `2 * totalLength - widget.startPadding;` when `startPadding` is 0. `_startPosition` is `2 * totalLength `, `totalLength` is expected to be '_getTextWidth() + widget.blankSpace;', when `blankSpace` is 0.  `totalLength ` is the width of input text.  But I doubt the following method is not caclulating the width right:

```dart
  double _getTextWidth() {
    final span = TextSpan(text: widget.text, style: widget.style);
    final tp = TextPainter(
      text: span,
      maxLines: 1,
      textDirection: TextDirection.ltr,
      //locale: Localizations.localeOf(context),
    );

    tp.layout(maxWidth: double.infinity);
    return tp.width;
  }
```
which causes `_controller.jumpTo(_startPosition);`  not jump the the start of text.
 
```dart
  Future<void> _makeRoundTrip() async {
    // Reset the controller, then accelerate, move linearly and decelerate.
    _controller.jumpTo(_startPosition);
    if (!_running) return;

    await _accelerate();
    if (!_running) return;

    await _moveLinearly();
    if (!_running) return;

    await _decelerate();
    if (!_running) return;

    await Future.delayed(widget.pauseAfterRound);
  }
```

**Comment by danieldai** [comment]
It’s not easy to get the width of text in flutter, will let you know, when I figure out how to do it.

**Comment by danieldai** [comment]
Here is a way to get the width of text right.
```
  final constraints = BoxConstraints(
    maxWidth: double.infinity, 
  );

  var text = '0123456789 1123456789 2123456789 3123456789';
  final span = TextSpan(text: text, style: TextStyle(color: Colors.white, fontSize: 26));

  final richTextWidget = Text.rich(span)
      .build(viewService.context) as RichText;
  final renderObject = richTextWidget.createRenderObject(viewService.context);
  renderObject.layout(constraints);

  final boxes = renderObject.getBoxesForSelection(TextSelection(
      baseOffset: 0, extentOffset: TextSpan(text: text).toPlainText().length));

  print('text width ${boxes.last.right}');
```

**Comment by danieldai** [comment]
I made a PR to fix this issue https://github.com/marcelgarus/marquee/pull/20

**Comment by marcelgarus** [comment]
Perfect, I merged it and I'll close this issue.
