### ISSUE TITLE
Version 1.3 is broken

### ISSUE THREAD

**Issue by humazed** [marcelgarus/marquee#19]
When using 1.3.0 the text doesn't scroll but when downgrading to 1.2.0 it works fine.

I can reproduce it even with the example.

**Comment by agyimr** [comment]
It does not work for me neither when I am trying on my android phone. I tried downgrading to 1.2 but it also did not start the animation.

**Comment by humazed** [comment]
are you using ^1.2.0 or 1.2.0
because the `^` downloads the latest version anyway.

**Comment by agyimr** [comment]
I checked and I was on 1.2.0 without the caret.

But I deleted the package and reinstalled it from my computer, and now it works. I don't know what got jammed in the first place...

**Comment by marcelgarus** [comment]
Strange. TBH, I'm not actively using this package anymore and involved in loads of other stuff, so this is not that high up on my todo list. 👀 Of course, you're welcome to debug the problem and file a pull request.

**Comment by danieldai** [comment]
I think this commit already fixed this issue https://github.com/marcelgarus/marquee/commit/f64cc07654190745b826fdc8c9bd954131c3748c

so it can be closed

**Comment by ishammahajan** [comment]
Hey @marcelgarus ! Thanks for the widget! Would you please update the version of the library which includes the above mentioned commit? I've locally made the change required to make things work, but another newcomer might not be able to. 

Thanks again! 😄

**Comment by marcelgarus** [comment]
Jup, updated it to 1.3.1.
