### ISSUE TITLE
Ability to fade the edges

### ISSUE THREAD

**Issue by arnaudelub** [marcelgarus/marquee#29]
It will be nice to have the ability to fade the edges (always or wether it's scrolling or not)
I can do a new PR if you like the idea, but for this, the widget has to be rebuild before and after each pause.
I'm also planing on using the plugin [fading_edge_scrollview](https://pub.dev/packages/fading_edge_scrollview) for this, so let me know.
Thanks

**Comment by arnaudelub** [comment]
here is the PR : #30

**Comment by marcelgarus** [comment]
Sure, sounds good to me.
I don't think rebuilding after every round will have a big performance impact, so that should be fine.
