### ISSUE TITLE
[Feature request] Start delay?

### ISSUE THREAD

**Issue by hacker1024** [marcelgarus/marquee#39]
Thanks for this plugin - it's great.

One addition that would be nice is a start delay feature. I'm embedding a marquee in a list tile, and it can be a little overwhelming to see every list tile start scrolling immediately after the list is presented.

I've seen start delays used in many other things that use marquees to solve this issue, and it'd be great to have in Flutter as well.

I'll try to make a PR myself.

**Comment by nt4f04uNd** [comment]
@hacker1024 close this
