### ISSUE TITLE
How can be use it with other page layout 

### ISSUE THREAD

**Issue by faridkzadeh** [marcelgarus/marquee#45]
I am new to Flutter. I have my page layout  as below. I just want to add notification to the last line. But I do not want to wrap my other widget (_buildTableCalendar and _buildListEvent) that will destroy my table.  
body: Center(
          child: ListView(
            children: [
              Column(mainAxisSize: MainAxisSize.max, children: <Widget>[
               _buildTableCalendar(),
              _buildListEvent()]

**Comment by marcelgarus** [comment]
The Marquee widget needs to be given bounded constraints. So, you should probably wrap the `Marquee` in an `Expanded` or a `SizedBox` with a fixed `height`.

> I am new to Flutter.

Here's a great intro into how constraints work in Flutter: https://flutter.dev/docs/development/ui/layout/constraints
