### ISSUE TITLE
Support fading text at both ends of the marquee

### ISSUE THREAD

**Issue by marcelgarus** [marcelgarus/marquee#6]

**Comment by danieldai** [comment]
ShaderMask can be used to achieve this feature

**Comment by marcelgarus** [comment]
After thinking about this, I don't believe this is in the scope of this widget.
Flutter is great because all the widgets are composable and if I tackle this challenge, it should probably be rather published as another package, perhaps named `fade_into_nothing` or something like that.

Then, code could look like this:

```dart
FadeIntoNothing(
  left: 8,
  right: 8,
  child: Marquee(...),
)
```

So, I'm gonna close this issue for now.
