### ISSUE TITLE
Problem with AppBar

### ISSUE THREAD

**Issue by chplalex** [marcelgarus/marquee#62]
Hello! I am trying to use Marquee with AppBar:

![image](https://user-images.githubusercontent.com/63255416/118293247-20c01580-b4e2-11eb-9f41-6b930564373c.png)

and I am getting the error:

![image](https://user-images.githubusercontent.com/63255416/118293921-d9865480-b4e2-11eb-8a99-326f5635a220.png)

What am I doing wrong?

**Comment by marcelgarus** [comment]
I think the `AppBar` allows the `Marquee` to be as big as possible, so the `Marquee` doesn't know how high it should be. The same problem would occur if you tried to use a vertically scrolling `ListView` as the `title`.

If you wrap the `Marquee` in a `SizedBox` with a height of `AppBar().prefferedSize.height`, that should resolve your issue.

**Comment by chplalex** [comment]
Thank you. It works good.

![image](https://user-images.githubusercontent.com/63255416/118626881-eb624300-b7d3-11eb-8729-4f348140e781.png)

**Comment by SheepYang1993** [comment]
It works
