### ISSUE TITLE
EasyLoading not work with marquee

### ISSUE THREAD

**Issue by jiabin87428** [marcelgarus/marquee#71]
When I Add a marquee to EasyLoading, refresh not working

**Comment by jiabin87428** [comment]
Use 'ScrollNotificationInterceptor'

**Comment by mdddj** [comment]
同样的问题，找到解决方案了吗

**Comment by jiabin87428** [comment]
> 同样的问题，找到解决方案了吗

找一下ScrollNotificationInterceptor的使用示例，这是用来解决滚动冲突的
