### ISSUE TITLE
Flutter 2.8.1 - ScrollController not attached to any scroll views error

### ISSUE THREAD

**Issue by aytunch** [MarcelGarus/marquee#76]
> [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 170 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
> #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> #2      ScrollController.jumpTo
> package:flutter/…/widgets/scroll_controller.dart:170
> #3      _MarqueeState.initState.<anonymous closure>
> package:marquee/marquee.dart:548
> #4      _MarqueeState.initState.<anonymous closure>
> package:marquee/marquee.dart:545
> #5      SchedulerBinding._invokeFrameCallback
> package:flutter/…/scheduler/binding.dart:1145

**Comment by danielkohl** [comment]
+1

**Comment by SergeyShustikov** [comment]
Fixed by rewrtining initState method 


 WidgetsBinding.instance?.addPostFrameCallback((_) async {
      if (!_running) {
        _running = true;
        if (_controller.hasClients) {
          _controller.jumpTo(_startPosition);
          await Future<void>.delayed(widget.startAfter);
          Future.doWhile(_scroll);
        }
      }
    });

**Comment by aytunch** [comment]
@SergeyShustikov @MarcelGarus Can we merge this fix to the package?

**Comment by MarcelGarus** [comment]
I merged this; it's published in version 2.2.1.
