### ISSUE TITLE
Flutter 3.0.0 is detecting issue with the library 

### ISSUE THREAD

**Issue by RoyalCoder88** [MarcelGarus/marquee#78]
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/marquee-2.2.1/lib/marquee.dart:545:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) async {

**Comment by MarcelGarus** [comment]
Thanks! I just published version 2.2.2, which supports Dart 2.18 and Flutter 3.

**Comment by RoyalCoder88** [comment]
Hi @MarcelGarus , thanks for your support and for your quick fix ;)

The **marquee** package depends on **fading_edge_scrollview**, who has the same issue with Flutter 3.0, can you remove please the dependencies of fading_edge_scrollview? Thanks in advance!

**Comment by MarcelGarus** [comment]
The marquee package actively uses fading_edge_scrollview, so it's impossible to remove the dependency without including major parts of its source code in marquee itself. You should take it up with that package's maintainer (I see you already did in https://github.com/mponkin/fading_edge_scrollview/issues/16).
