### ISSUE TITLE
Compiler warnings on Flutter 3.0

### ISSUE THREAD

**Issue by jannisnikoy** [MarcelGarus/marquee#79]
While the marquee library has been updated with Flutter 3.0 support, it still refers to an older version of the fading_edge_scrollview dependency which lacks 3.0 support. This dependency should be updated to version 3.0.0 to resolve all compiler warnings when using Flutter 3.0

**Comment by PranayD1807** [comment]
This needs to be implemented asap

**Comment by PranayD1807** [comment]
Fading_edge_scrollview has now been fixed and updated according to 3.0.0 ,
Please update the dependency in this package.

**Comment by MarcelGarus** [comment]
This should be fixed in version 2.2.3.
