### ISSUE TITLE
Support custom CrossAxisAlignment

### ISSUE THREAD

**Issue by marcelgarus** [marcelgarus/marquee#8]

**Comment by izayl** [comment]
any progress about this feature? @marcelgarus

**Comment by marcelgarus** [comment]
Not yet, and I'm currently a bit busy, but I'll try to look into it in the coming week or so.
Btw, if anyone wants to implement it, you're welcome to assign yourself and work on it. I'm more than happy to accept pull requests.

**Comment by marcelgarus** [comment]
Phew, completely forgot about that.
CrossAxisAlignment is now supported 🎉
